### ISSUE TITLE
Adding molecular dynamic simulation

### ISSUE THREAD

**Issue by dlsrnsi** [AngelRuizMoreno/Jupyter_Dock#4]
Dear, Angel Ruiz Moreno

Thank you for your nice tutorial notebook. It really helped me a lot

If you are okay with it, can you add molecular dynamic simulation tutorial in this repository?

It will help many researchers

Thank you again.

Sincerely, 

Ingoo Lee

**Comment by AngelRuizMoreno** [comment]
Dear Ingoo, 

Thank you for your comment and request. 

For the time being, I am not considering including MD in this repo because it is primarily concerned with Molecular Docking. There are, however, some very useful and interesting repositories for running MD in Google Colabs (https://github.com/AngelRuizMoreno/making-it-rain).

Examine it to see if it satisfies your objectives.

Best wishes.

Angel

**Comment by AngelRuizMoreno** [comment]
Closed
